#!/usr/bin/env bash

# install.sh generated by @project.artifactId@ v@project.version@

CURRENT="%(pwd)"
TARGET="${install.directory}"

if [ -d "%{TARGET}" ]; then
    echo "Zipping current contents of '%{TARGET}'."
    zip -r "%{TARGET}-%(date +'%Y-%m-%d-%H-%M-%S').zip" "%{TARGET}"
else
    echo "Creating '%{TARGET}'."
    mkdir -p "%{TARGET}"
fi

echo "Copying files to '%{TARGET}'."
cp -r . "%{TARGET}" || exit 1

echo "Changing owner."
chown -R ${unit.user}:${unit.user} "%{TARGET}"

echo "Installing systemd unit '${unit.fileName}'."
cd "%{TARGET}"
chmod u+x ./${run.fileName}
./${run.fileName} install